# git-cliff ~ configuration for changelog generation
# https://git-cliff.org/docs/configuration
#
# Used by:
# - release-plz: for ic-btc-interface and ic-btc-validation (semver)
# - release-pr.yml workflow: for ic-btc-canister and watchdog (date-based)

[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
body = """
{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | split(pat="\n") | first | upper_first | trim }}
    {% endfor %}
{% endfor %}\n
"""
footer = """
{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/dfinity/bitcoin-canister\
                    /compare/{{ release.previous.version }}...{{ release.version }}
        {% else -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/dfinity/bitcoin-canister\
                    /releases/tag/{{ release.version }}
        {% endif -%}
    {% else -%}
        {% if release.previous.version -%}
            [Unreleased]: https://github.com/dfinity/bitcoin-canister\
                /compare/{{ release.previous.version }}...HEAD
        {% endif -%}
    {% endif -%}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^feat", group = "Added" },
    { message = "^[a|A]dd", group = "Added" },
    { message = "^[s|S]upport", group = "Added" },
    { message = "^.*: add", group = "Added" },
    { message = "^.*: support", group = "Added" },
    { message = "^[r|R]emove", group = "Removed" },
    { message = "^.*: remove", group = "Removed" },
    { message = "^.*: delete", group = "Removed" },
    { message = "^fix", group = "Fixed" },
    { message = "^.*: fix", group = "Fixed" },
    { message = "^test", group = "Fixed" },
    { message = "^security", group = "Security" },
    { message = "^.*: security", group = "Security" },
    { message = "^.*", group = "Changed" },
]
filter_commits = false
topo_order = false
sort_commits = "newest"
