[package]
name = "scenario-1"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.28.1"
candid = "0.9.0-beta.3"
ic-btc-test-utils = { path = "../../test-utils" }
ic-cdk = "0.8.1"
ic-cdk-macros = "0.8.0-beta.0"
serde = "1.0.132"
