[package]
name = "ic-btc-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }

[dev-dependencies]
ciborium = { workspace = true }
proptest = { workspace = true }
